# Generated by Django 3.1.3 on 2020-11-13 20:23

import app.models
import app.utils.misc
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                ("guid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                (
                    "input_file",
                    models.FileField(
                        upload_to=app.models.MediaFile.get_upload_path,
                        validators=[app.utils.misc.validate_file_size, app.utils.misc.validate_file_name],
                    ),
                ),
                ("output_file", models.FileField(null=True, upload_to="")),
                (
                    "output_format",
                    models.CharField(
                        choices=[("mp4", "MP4"), ("mov", "MOV"), ("mpg", "MPG"), ("avi", "AVI")], max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOAD_COMPLETE", "UPLOAD_COMPLETE"),
                            ("CONVERTING", "CONVERTING"),
                            ("FAILED", "FAILED"),
                            ("DONE", "DONE"),
                        ],
                        default="UPLOAD_COMPLETE",
                        max_length=16,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
